name: Sync GitHub to Gitee

on:
  pull_request:
    branches-ignore:
      - ''
  push:
    branches-ignore:
      - ''
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Mirror the GitHub repo to Gitee
        uses: Yikun/hub-mirror-action@v1.4
        with:
          src: github/FCL-Team
          dst: gitee/FCL-Team
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: 'FCL-Controllers'
          account_type: org
          force_update: true
          timeout: 300
          debug: false